return {
    lsp = {
        ['bashls'] = {
            -- lsp settings
        },
        --'biome', -- JS/TS, JSX/TSX, JSON/JSONC
        ['clangd'] = {},
        ['cssls'] = {},
        ['cssmodules_ls'] = {},
        --'dprint',
        ['html'] = {},
        ['jsonls'] = {},
        ['lua_ls'] = {},
        ['markdown_oxide'] = {},
        ['marksman'] = {},
        ['rust_analyzer'] = {},
        ['taplo'] = {},
        ['tsserver'] = {},
        ['yamlls'] = {},
    },
    formatter = {
        ['shfmt'] = {},
        ['stylua'] = {},
    },
    dap = {},
    treesitter = {
        'bash',
        'c',
        'comment',
        'cpp',
        'css',
        'csv',
        'diff',
        'glsl',
        'graphql',
        'html',
        'javascript',
        'jsdoc',
        'json',
        'json5',
        'jsonc',
        'jsonnet',
        'kdl',
        'lua',
        'luadoc',
        'luap',
        'markdown',
        'markdown_inline',
        'printf',
        'racket',
        'regex',
        'rust',
        'sql',
        'toml',
        'tsx',
        'typescript',
        'vim',
        'vimdoc',
        'xml',
        'yaml',
    },
}
